#!/usr/bin/php
<?php

new dockerDkManager($argv);
class dockerDkManager
{

    public function __construct($argv)
    {

        $this->__MAIN__($argv);
    }


    public function __MAIN__($args)
    {

        while (true) {

            $this->printMenu();

            // Read user choice
            $choice = trim( fgets(STDIN) );
            echo  "\e[33m ";
            switch ($choice) {
                case "0":
                    exit;
                    break;

                case "1":
                    passthru("docker rm -f $(docker ps -a -q)");
                    break;
                case "2":
                    passthru("docker rmi -f $(docker images -a -q)");
                    break;
                case "3":
                    passthru("docker volume rm $(docker volume ls -q)");
                    break;
                case "4":
                    passthru("docker network rm $(docker network ls | tail -n+2 | awk '{if($2 !~ /bridge|none|host/){ print $1 }}')");
                    break;

                case "10":

                    passthru("docker ps --all --format \"table {{.ID}}\t{{.Names}}\"");
                    break;

                case "11":

                    passthru("docker ps --all --format \"table {{.ID}}\t{{.Names}}\"");
                    echo  "\e[32m ";
                    echo "Enter your container name / id or 0 to exit::";
                    echo  "\e[0m";
                    echo "\n";
                    $container = trim( fgets(STDIN) );

                    if($container==0)
                        continue;

                    passthru("docker exec -it ".$container." /bin/bash ");
                    break;
            }
            echo  "\e[0m";


        }
    }


    public function printMenu()
    {
        echo  "\e[34m ";
        echo "************ Docker Manager System ******************\n";
        echo "0 - Quit\n";
        echo "1 - Remove Containers \n";
        echo "2 - Remove Imagens \n";
        echo "3 - Remove Volumes \n";
        echo "4 - Remove Networks \n";
        echo "10 - Return  Container Names \n" ;
        echo "11 - Enter in container with NAME or ID \n" ;
        echo "************ Docker Manager System ******************\n";
        echo  "\e[0m";

        echo  "\e[32m ";
        echo "Enter your choice from 1 to 11 ::";
        echo  "\e[0m";



    }




}



